### ISSUE TITLE
Avoid node clipping with CairoMakie.jl as backend

### ISSUE THREAD

**Issue by mroavi** [JuliaPlots/GraphMakie.jl#35]
Hi. I'm trying to generate a figure for a paper using GraphMakie.jl and CairoMakie.jl. I'm stuck with a small issue since I'm not very familiar with Makie.jl yet: In the image below, how can I avoid the clipping of the nodes in the corners?

![06-grid3x3](https://user-images.githubusercontent.com/19517248/135937804-2c66e889-2c64-4edc-bc04-6639ec5322b7.png)

I noticed that this is easy to fix using GLMakie using the mouse wheel to control the zoom:

![image](https://user-images.githubusercontent.com/19517248/135937881-d00b0ea4-cd4a-47d5-bddb-45f7eac07e0c.png)

However, I haven't been able to emulate this programatically to make it work with CairoMakie.jl.

**Comment by mroavi** [comment]
Giving this a bit of afterthought, I think it would be a good idea to make the layout placement of the nodes aware of the size of the nodes themselves to avoid this clipping, for example by adding some kind of margin/padding. What do you think?

**Comment by hexaeder** [comment]
Well this has to do with the automatic axis limit calculation in Makie. You can manually set the limits using
```julia
xlims!(0, 1)
ylims!(0, 1)
```
Unfortunately this is not possible from inside the `graphplot` recipe because we can't access the `Axis` object from within.

In theory it would be really great to depend the layouts on the node sizes and stuff. Not so easy though. For example we use `scatter` which plots dots in pixel space on the screen. The layout happens in data space. The correlation between the both depends on zoom and aspect ratios.

**Comment by mroavi** [comment]
Thanks for the workaround!
