### ISSUE TITLE
Simpler curvy edges 

### ISSUE THREAD

**Issue by greimel** [JuliaPlots/GraphMakie.jl#37]
Is it possible to bend edges like below automatically? If not, would a PR be welcome?

![image](https://user-images.githubusercontent.com/6280307/137282469-5a677bf5-0fae-47c6-bea3-d76fc94bae98.png)

```julia
let	
	function points_on_circle(n, c = Point(0, 0))
		x = range(0, 2, n + 1)
		x = x[2:end]
	
		Point2.(sinpi.(x), cospi.(x)) .+ Ref(c)
	end
	
	function rotate_vector(pt::Point2, α)
		x, y = pt
		sα, cα = sincos(α)
		Point2(x * cα - y * sα, x * sα + y * cα)
	end

	function get_tangents(g, node_locs, α=0.1)
		map(edges(g)) do edge
			diff = node_locs[dst(edge)] - node_locs[src(edge)]
			tangents = rotate_vector.(Ref(diff), [α, -α])
		end
	end
	
	g = SimpleWeightedDiGraph([
			0 1 1;
			2 0 1;
			2 2 0
			])
	
	node_locs = points_on_circle(nv(g))
	layout = _ -> node_locs
	tangents = get_tangents(g, node_locs, 0.1)
	edge_width = weight.(edges(g))
	graphplot(g;
		tangents, layout, edge_width,
		axis = (aspect = DataAspect(), )
	)
	

end
```

**Comment by filchristou** [comment]
I need to agree that it is not very convenient drawing the Bezier curves for big networks.
I think a major improvement can be easily made if the `tangents` points are given not only as relative to the `src`.`dst` node positions but also relative to the coordination system defined by a cartesian coordinating system with the x axis being the direct straight edge from `src` to `dst`. This way only a coordinate transormation needs to be made before drawing the bezier graphs. This should also trigger digraph edges to be symmetrical if same `tangents` are given.

**Comment by hexaeder** [comment]
I've implement my sketch above in #48 . What do you think?

**Comment by greimel** [comment]
That's amazing! Thank you!

(And sorry for not having pursued this any further.)

**Comment by filchristou** [comment]
I also think it's a nice feature. Allow me to collaborate a little bit more on what I meant.
Right now tangents being passed are treated with a rather counter-intuituve reference system, which for me makes it impossible to directly pass in the correct values.
See the picture attached for an explanation:
![tangentsmakie](https://user-images.githubusercontent.com/27723218/149655655-66cf69bc-4237-4726-9016-45d89a2c084e.jpeg)

Given a bezier point (p1, p2) now, p1 is being treated according to `x1-y1` and p2 according to `x2-y2`. That being said the reference system is irrelative to the direct edge connecting the two nodes.
I think a rotation could be used to make the reference system of point p1 be `x1'-y1'` and from p2 `x2'-y2'`, thus dependant on the direct interconnecting edge.

This can lead to much more intuituve plotting. Please have a look to the pluto notebook (shared as a .gz)
[eZtangets.jl.html.gz](https://github.com/JuliaPlots/GraphMakie.jl/files/7876706/eZtangets.jl.html.gz)
or as pdf file: [eZtangents.pdf](https://github.com/JuliaPlots/GraphMakie.jl/files/7876709/eZtangents.pdf)

**Comment by filchristou** [comment]
when the interconnecting edge is not horizontal or vertical I see that there is some offset, making it not completely symmetrical. It can be seen in the last plot in the notebook

**Comment by hexaeder** [comment]
Yeah you totally have a point there! For context, I've created the tangents interface to allow for this plot:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/35867212/149656724-6ade838a-5e04-4b36-8297-cd0a6f2c7f4c.png">
For that specific usescase the global coordinate system is the right choice. I'd also argue that the word `tangent` implies a global coordinate system since tangents are usually defined in that space. It is also the only option which extends easily to 3D.

However, we totally need a way of specifying this "locally:" the big question is the right kind of interface. I don't want to add 10 different methods for drawing curvy edges, i think this will be confusing.

Distance from straight line: this is implementend in the PR. I think it is the most straight forward interface. There is a "right" distance for the control points such as the resulting spline looks like a circle segment [1], which is probably the best look for this kind of graphs. The use should not care about this. In order to deal with [1] one might add another parameter, `distance_space=:data` and `distance_space=:pixel`.

I think there is also a need for a more low level interface to place the control points (for example in a rotated coordinate system as you suggested). Do you think it would be beneficial to have this in cartesian coordinates? Another way would be to specify an angle and a distance per control point.
Maybe it would be also sufficient to provide a real low level interface: the user could provide a function `f(src, dst, i)->(c1, c2)` which gets the positions of the source and destination vertex of the i-th edge and returns a tuple of two control points, than it would be relatively easy to implement whatever you like.

[1] There is a subtle difference between pixel space and data space here which is not implemented in the PR. I guess thats also the reason why your last example plot looks kinda asymetric. Try with `ax.aspect = DataAspect()`.

**Comment by hexaeder** [comment]
One could even go all in on the `f(src, dst, i) -> (c1, c2)` interface. Getting rid of all of the other options and provide prebuild functions such as:
- `waypoint_edge([p1, p2,...])`
- `simple_curvy_edge(distance; space=[:pixel, :data])`
- `global_tangents(...)`
- `local_tangents(...)`

Hm but given that 2/3 of questions regarding GraphMakie are due to the layout interface this kind of interface does not seem to be intuitive for a lot of users.

**Comment by filchristou** [comment]
> [1] There is a subtle difference between pixel space and data space here which is not implemented in the PR. I guess thats also the reason why your last example plot looks kinda asymetric. Try with ax.aspect = DataAspect().

Yes, Now it looks fully symmetrical. true!

Regarding "local" and "global" perpective, I guess both are kind of local (translated to the `src` or `dst` node), but the "global" holds on to the same global directions, while the "local"  in addition rotates about the `dst-src` vector.
I see that in your example the "global" view is needed.

> Another way would be to specify an angle and a distance per control point

Actually I think that such a relative polar system would be a more straightforward choice and more easy to configure.

For my use case `curve_distance` would suffice, and probably is also the simplest to use. But for drawing more fancy graphs, indeed a lower level "local" or "global" interface is needed. Putting everything as a key-value argument in the `graphplot` function, it will bring much unneeded confusion.

I actually see the tangents as part of the more general `layout`. And given that the `layout` also expects an input function, `tangents` could work similarly as you proposed getting a function `f(src, dst, i)->(c1, c2)`. Some default functions (or tools like "global" or "local" view) can be given, in the same way that there are default functions for the layout.
