### ISSUE TITLE
interface `edge_paths` of the recipe to user

### ISSUE THREAD

**Issue by filchristou** [JuliaPlots/GraphMakie.jl#76]
Hi,

I want to highlight some edges and I find it hard to recalculate the `Vector{AbstractPath}`
What I want to do is the following:
```julia
gc = circular_ladder_graph(5) |> DiGraph
f,a,p = graphplot(gc, elabels = repr.(edges(gc)), nlabels=repr.(vertices(gc)))
edgeplot!(a, p.edge_paths[][4:9], linewidth=15, color=(:red,0.5))
```
which will draw the following:
![image](https://user-images.githubusercontent.com/27723218/161615859-c261b9a3-ebb4-4f7b-b860-72e940c9aa74.png)

It's fairly easy when `edge_paths` is given available to the user.

Otherwise I must call `find_edge_paths` which also expects some `Attributes` value, which is rather complicated.
Is there a more sophisticated way?

**Comment by hexaeder** [comment]
something like this is done in a hacky way for the `node_pos`. Hacky, because adds the observable to the attributes of the plot object from inside the recipe.

https://github.com/JuliaPlots/GraphMakie.jl/blob/a1ab3f931c6c023644fdd1f226b11b9a87eaa941/src/recipes.jl#L176

If i remember correctly, there were some difficulties. I.e it works like this
```julia
g[:attr] = @lift ...
local_attr = g[:attr]
```
but not like this
```julia
local_attr = @lift ...
g[:attr] = local_attr
```

should be fine to use the same strategy here

https://github.com/JuliaPlots/GraphMakie.jl/blob/a1ab3f931c6c023644fdd1f226b11b9a87eaa941/src/recipes.jl#L195-L200

**Comment by filchristou** [comment]
Yes, in order to draw the figure above, I followed the example of `node_pos`
```diff
diff --git a/src/recipes.jl b/src/recipes.jl
index 9714263..2881510 100644
--- a/src/recipes.jl
+++ b/src/recipes.jl
@@ -194,10 +194,11 @@ function Makie.plot!(gp::GraphPlot)
 
     # create array of pathes triggered by node_pos changes
     # in case of a graph change the node_position will change anyway
-    edge_paths = lift(node_pos, gp.selfedge_size,
+    gp[:edge_paths] = lift(node_pos, gp.selfedge_size,
                       gp.selfedge_direction, gp.selfedge_width) do pos, s, d, w
         find_edge_paths(graph[], gp.attributes, pos)
     end
+    edge_paths = gp[:edge_paths]
 
     # plot edges
     edge_plot = edgeplot!(gp, edge_paths;
```
"Hacky" is kind of a scary word. 
My impression for "Hacky" stuff is that they tend to go unstable between releases and most of the times do not follow best practices.
Do you know if there is a better way to do it or it is indeed the suggested technique in the `Makie` ecosystem ?
